swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API de Autenticación y Sesión'
paths:
  /register:
    post:
      summary: Registrar un nuevo usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/User'
      responses:
        '200':
          description: Usuario registrado exitosamente
        '400':
          description: Error de validación o usuario ya existente
        '500':
          description: Error interno del servidor

  /login:
    post:
      summary: Iniciar sesión
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/LoginCredentials'
      responses:
        '200':
          description: Sesión iniciada correctamente
        '400':
          description: Credenciales inválidas
        '401':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /logout:
    post:
      summary: Cerrar sesión
      tags:
        - Auth
      responses:
        '200':
          description: Sesión cerrada correctamente
        '500':
          description: Error interno del servidor

  /profile:
    get:
      summary: Obtener perfil de usuario
      tags:
        - Profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Perfil de usuario obtenido exitosamente
        '401':
          description: No autorizado (token inválido)
        '500':
          description: Error interno del servidor

definitions:
  User:
    type: object
    properties:
      name:
        type: string
      lastName:
        type: string
      email:
        type: string
      age:
        type: integer
      password:
        type: string
    required:
      - name
      - lastName
      - email
      - age
      - password

  LoginCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
